### ISSUE TITLE
Enchancment 🥇 

### ISSUE THREAD

**Issue by wyattfre** [JGray0705/UserScripts#2]
Hey @JGray0705 I want to thank you for your hard work in making these amazing codes for TM. Just a quick question, is there anyway you could possibly make the 'send message' line longer in the find_people? It would be amazing if that was a possibility, and make life so much easier! 

Also, In the Sauron Dashboard, we love using your progress checker, is there anyway you can make the 100% rainbow? Just a weird question, but you have done such an amazing job! Thank you!!

**Comment by JGray0705** [comment]
How much longer are you thinking? This is definitely possible. As for the Sauron, I can't think of any simple way to 🌈
